{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "y9AXg1rU9hcc",
        "outputId": "9ed12ecd-a99e-4c62-a937-2719c3cb7085"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.38.0-py2.py3-none-any.whl.metadata (8.5 kB)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n",
            "Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.26.4)\n",
            "Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.1)\n",
            "Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.1.4)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (10.4.0)\n",
            "Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (14.0.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.8.1)\n",
            "Collecting tenacity<9,>=8.1.0 (from streamlit)\n",
            "  Downloading tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.12.2)\n",
            "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
            "  Downloading GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)\n",
            "Collecting watchdog<5,>=2.1.5 (from streamlit)\n",
            "  Downloading watchdog-4.0.2-py3-none-manylinux2014_x86_64.whl.metadata (38 kB)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)\n",
            "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Downloading gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2024.2)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)\n",
            "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Downloading smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.20.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n",
            "Downloading streamlit-1.38.0-py2.py3-none-any.whl (8.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m8.7/8.7 MB\u001b[0m \u001b[31m31.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading GitPython-3.1.43-py3-none-any.whl (207 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m207.3/207.3 kB\u001b[0m \u001b[31m10.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m56.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading tenacity-8.5.0-py3-none-any.whl (28 kB)\n",
            "Downloading watchdog-4.0.2-py3-none-manylinux2014_x86_64.whl (82 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m82.9/82.9 kB\u001b[0m \u001b[31m4.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading gitdb-4.0.11-py3-none-any.whl (62 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.7/62.7 kB\u001b[0m \u001b[31m3.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading smmap-5.0.1-py3-none-any.whl (24 kB)\n",
            "Installing collected packages: watchdog, tenacity, smmap, pydeck, gitdb, gitpython, streamlit\n",
            "  Attempting uninstall: tenacity\n",
            "    Found existing installation: tenacity 9.0.0\n",
            "    Uninstalling tenacity-9.0.0:\n",
            "      Successfully uninstalled tenacity-9.0.0\n",
            "Successfully installed gitdb-4.0.11 gitpython-3.1.43 pydeck-0.9.1 smmap-5.0.1 streamlit-1.38.0 tenacity-8.5.0 watchdog-4.0.2\n"
          ]
        }
      ],
      "source": [
        "! pip install streamlit\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile app.py"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3wDJKASNACXX",
        "outputId": "1ca5e963-28f7-445a-9547-ac1ea66dbf12"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Writing app.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! wget -q -O - ipv4.icanhazip.com"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Ip_ipG6GAKfN",
        "outputId": "e4135883-a3a8-4912-a569-6e9462f6a5de"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "104.196.180.111\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! streamlit run app.py & npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rTlUEAUBAZdN",
        "outputId": "0c51fa06-445d-4e3c-cc31-1d948cadc58e"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Local URL: \u001b[0m\u001b[1mhttp://localhost:8501\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://104.196.180.111:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[1G\u001b[0JNeed to install the following packages:\n",
            "  localtunnel@2.0.2\n",
            "Ok to proceed? (y) \u001b[20Gy\n",
            "\u001b[K\u001b[?25hyour url is: https://spotty-papayas-divide.loca.lt\n",
            "y\n",
            "2024-09-21 15:35:13.388 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:35:39.107 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:35:58.623 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:05.483 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:12.168 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:15.868 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:20.319 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:24.995 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:27.426 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:31.157 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:36:35.361 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 85, in <module>\n",
            "    sunburst_chart = px.sunburst(filtered_sunburst_data,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 1541, in sunburst\n",
            "    return make_figure(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'path_1' is not the name of a column in 'data_frame'. Expected one of ['Town', 'Total'] but received: Facility\n",
            "2024-09-21 15:59:56.415 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:00:28.586 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:00:35.756 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:00:41.182 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:00:48.650 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:00:52.710 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:01:02.318 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:01:24.491 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n",
            "2024-09-21 16:01:29.256 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 88, in exec_func_with_error_handling\n",
            "    result = func()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 590, in code_to_exec\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 107, in <module>\n",
            "    st.write(f\"- The bar chart allows you to explore the total number of {facility_selected} across all towns. You can filter towns based on a minimum threshold for more targeted analysis.\")\n",
            "NameError: name 'facility_selected' is not defined\n"
          ]
        }
      ]
    }
  ]
}